# используем язык java. Travis CI поддерживает другие языки тоже.
language: android
dist: trusty
android:
  components:
    - build-tools-29.0.2
    - android-29

# используем режим обычного пользователя для сборки проекта.
sudo: false

script:
  - ./gradlew build assembleDebug

before_install:
  - chmod +x gradlew
  - yes | sdkmanager "platforms;android-29"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      -tema9991@mail.ru
    on_success: never # default: change
    on_failure: always # default: always

env:
  global:
    - CODECOV_TOKEN="baf01638-c7b8-40c4-affe-42d29afe5642"