language: android
dist: trusty
jdk: oraclejdk8
sudo: false
env:
  global:
    - ANDROID_API=29
    - EMULATOR_API_LEVEL=21
    - ANDROID_BUILD_TOOLS=29.0.2
    - ADB_INSTALL_TIMEOUT=20
    - ANDROID_ABI=armeabi-v7a
android:
  components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS
    - android-$ANDROID_API
    - android-$EMULATOR_API_LEVEL
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19
    - sys-img-$ANDROID_ABI-$EMULATOR_API_LEVEL
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
script:
  - ./gradlew build jacocoTestReport assembleAndroidTest
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
  - ./gradlew connectedCheck
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    recipients:
      -tema9991@mail.ru
    on_success: never # default: change
    on_failure: always # default: always
