language: android
dist: trusty
jdk: oraclejdk8
sudo: false
env:
  global:
    - ANDROID_API=29
    - EMULATOR_API_LEVEL=21
    - ANDROID_BUILD_TOOLS=29.0.2
    - ADB_INSTALL_TIMEOUT=20
    - ANDROID_ABI=armeabi-v7a
    - CODECOV_TOKEN="baf01638-c7b8-40c4-affe-42d29afe5642"
android:
  components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS
    - android-$ANDROID_API
    - android-$EMULATOR_API_LEVEL
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19
    - sys-img-armeabi-v7a-addon-google_apis-google-$ANDROID_API_LEVEL
    - sys-img-armeabi-v7a-addon-google_apis-google-$EMULATOR_API_LEVEL
    - sys-img-armeabi-v7a-android-$EMULATOR_API_LEVEL
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    recipients:
      -tema9991@mail.ru
    on_success: never # default: change
    on_failure: always # default: always